[build]
  command = "echo 'Build complete'"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/county_data"
  to = "/.netlify/functions/county_data"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9"
